behaviors:
  ChairWalker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 32768
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.01
        network_settings:
          hidden_units: 64
          num_layers: 3
        learning_rate: 0.0001
    keep_checkpoints: 20
    max_steps: 80000000
    time_horizon: 1000
    summary_freq: 100000
environment_parameters:
  stair_height:
    curriculum:
      - name: Lesson0 # Start of second lesson
        completion_criteria:
          measure: reward
          behavior: ChairWalker
          signal_smoothing: true
          min_lesson_length: 100.0
          threshold: 1500
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.5
            max_value: 1.0
      - name: Lesson1 # Start of second lesson
        completion_criteria:
          measure: reward
          behavior: ChairWalker
          signal_smoothing: true
          min_lesson_length: 100.0
          threshold: 1500
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 1.0
            max_value: 2.0
      - name: Lesson1 # Start of second lesson
        completion_criteria:
          measure: reward
          behavior: ChairWalker
          signal_smoothing: true
          min_lesson_length: 100.0
          threshold: 1500
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 2.0
            max_value: 3.0
      